// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MicasitaPropietarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void micasitaPropietario() {
    driver.get("http://localhost:4200/register");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Juan");
    driver.findElement(By.name("dni")).click();
    driver.findElement(By.name("dni")).sendKeys("11111111");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("juan@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123456789");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("987654321");
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("AV.MARIAN San Miguel");
    driver.findElement(By.cssSelector("button:nth-child(9)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mdc-button > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-mdc-menu-trigger > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".mat-mdc-menu-trigger > .mat-mdc-button-touch-target")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-mdc-menu-item:nth-child(1) .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-mdc-menu-item:nth-child(2) .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
    driver.findElement(By.id("mat-input-0")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-stepper-next:nth-child(1) > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-stepper-next:nth-child(1) > .mdc-button__label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("mat-input-0")).sendKeys("Juan");
    driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#venta .mdc-label")).click();
    driver.findElement(By.cssSelector("#mat-select-value-1 > .mat-mdc-select-placeholder")).click();
    driver.findElement(By.cssSelector("#mat-option-0 > .mdc-list-item__primary-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .mat-stepper-previous > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .mat-stepper-next > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .mat-stepper-next:nth-child(2) > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#mat-select-value-3 > .mat-mdc-select-placeholder")).click();
    driver.findElement(By.cssSelector("#mat-option-6 > .mdc-list-item__primary-text")).click();
    driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
    driver.findElement(By.cssSelector(".mat-mdc-select-placeholder")).click();
    driver.findElement(By.id("mat-option-29")).click();
    driver.findElement(By.id("sol-input")).click();
    driver.findElement(By.id("mat-input-1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".files-container_case-1 .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".files-container_case-1 .mdc-button__label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("mat-input-1")).sendKeys("1498");
    driver.findElement(By.cssSelector(".cdk-focused > .mdc-button__label")).click();
    driver.findElement(By.id("fileInput")).sendKeys("C:\\fakepath\\images2.jpg");
    driver.findElement(By.id("mat-input-2")).click();
    driver.findElement(By.id("mat-input-2")).sendKeys("15");
    driver.findElement(By.id("mat-input-3")).click();
    driver.findElement(By.id("mat-input-3")).sendKeys("3");
    driver.findElement(By.id("mat-input-4")).click();
    driver.findElement(By.id("mat-input-4")).sendKeys("2");
    driver.findElement(By.id("mat-input-5")).click();
    driver.findElement(By.id("mat-input-5")).sendKeys("0");
    driver.findElement(By.id("mat-input-6")).click();
    driver.findElement(By.id("mat-input-6")).sendKeys("Propiedad frente a la Universidad");
    driver.findElement(By.id("mat-input-7")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".submit-button > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("mat-input-7")).sendKeys("Es un espacio amplio, comodo y el lugar es seguro.");
    driver.findElement(By.cssSelector(".submit-button > .mdc-button__label")).click();
    driver.findElement(By.cssSelector(".submit-button > .mdc-button__label")).click();
  }
}
